title: 追求真空
description: 用心编程，用心写文章
meta_description: "追求真空个人博客，编程学习心得分享"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://brucegui.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://brucegui.github.io'
author:         '追求真空'
authorTwitter:  'ziwo520'

permalink:       /:year/:title/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about  
