title: 追求真空
subtitle: Programming-Make Life More Easy.
description: 用心编程，用心写文章
meta_description: "追求真空个人博客，编程学习心得分享"

markdown: kramdown
highlighter: rouge

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 20
domain_name: 'https://soragui.com' 
disqus: true
disqus_shortname: 'ziwo520'
social:
  twitter: ziwo520
  github: soragui

# Details for the RSS feed generator
url:            'https://soragui.com'
author:         soragui 

permalink:       /:year/:title/

theme_settings:
  special_page:
    search:
      enabled: false
 
