title: 追求真空
description: 用心编程，用心写文章
meta_description: "追求真空个人博客，编程学习心得分享"
 
markdown: kramdown
highlighter: rouge

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 20
domain_name: 'https://brucegui.github.io' 
disqus: true
disqus_shortname: 'your-disqus-shortname'
social:
  twitter: ziwo520
  github: soragui
  email: ziwo520@gamil.com

# Details for the RSS feed generator
url:            'https://brucegui.github.io'
author:         soragui 

permalink:       /:year/:title/

navigation:
 - title: Home
   url: /index.html   
