title: 追求真空
subtitle: 编程让生活更轻松.
description: 用心编程，用心写文章
meta_description: "追求真空个人博客，编程学习心得分享"

markdown: kramdown
highlighter: rouge

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 20
domain_name: 'https://soragui.com' 
disqus: soragui
social:
  name: 追求真空
  twitter: https://twitter.com/ziwo520
  github: https://github.com/soragui

# Details for the RSS feed generator
url:            'https://soragui.com'
author:         soragui 

permalink:       /:year/:title/
#menu:
#  - title: 'Blog'
#    url: '/posts'
# seo setting
logo: assets/images/logo.png
twitter:
  username: ziwo520
  card: summary
 

